// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dcn.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// message
type Message struct {
	Main                 int32    `protobuf:"varint,1,opt,name=main,proto3" json:"main,omitempty"`
	Sub                  int32    `protobuf:"varint,2,opt,name=sub,proto3" json:"sub,omitempty"`
	Pub                  []byte   `protobuf:"bytes,3,opt,name=pub,proto3" json:"pub,omitempty"`
	Sig                  []byte   `protobuf:"bytes,4,opt,name=sig,proto3" json:"sig,omitempty"`
	Body                 []byte   `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_b80de7960cdf08a7, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMain() int32 {
	if m != nil {
		return m.Main
	}
	return 0
}

func (m *Message) GetSub() int32 {
	if m != nil {
		return m.Sub
	}
	return 0
}

func (m *Message) GetPub() []byte {
	if m != nil {
		return m.Pub
	}
	return nil
}

func (m *Message) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "proto.Message")
}

func init() {
	proto.RegisterFile("dcn.proto", fileDescriptor_b80de7960cdf08a7)
}

var fileDescriptor_b80de7960cdf08a7 = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x49, 0xce, 0xd3,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xe9, 0x5c, 0xec, 0xbe, 0xa9, 0xc5,
	0xc5, 0x89, 0xe9, 0xa9, 0x42, 0x42, 0x5c, 0x2c, 0xb9, 0x89, 0x99, 0x79, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0xac, 0x41, 0x60, 0xb6, 0x90, 0x00, 0x17, 0x73, 0x71, 0x69, 0x92, 0x04, 0x13, 0x58, 0x08,
	0xc4, 0x04, 0x89, 0x14, 0x94, 0x26, 0x49, 0x30, 0x2b, 0x30, 0x6a, 0xf0, 0x04, 0x81, 0x98, 0x60,
	0x35, 0x99, 0xe9, 0x12, 0x2c, 0x10, 0x91, 0xe2, 0xcc, 0x74, 0x90, 0x49, 0x49, 0xf9, 0x29, 0x95,
	0x12, 0xac, 0x60, 0x21, 0x30, 0x3b, 0x89, 0x0d, 0x6c, 0x9f, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0xcf, 0x21, 0x7b, 0xc5, 0x83, 0x00, 0x00, 0x00,
}
